---
  run_name: RidgeRegression
  data_file: /home/daviden1013/David_projects/Qualifying_exam_C/data/curated_df.pkl
  model: RidgeRegression
  out_path: /home/daviden1013/David_projects/Qualifying_exam_C/